### PR TITLE
Adding line breaks after an image.

### PR DESCRIPTION
**Pull request by ryanwelcher**
When inserting an image and outputting markdown, there is no break after the images. See https://github.com/ryanwelcher/vscode-readme-editor/issues/4 for example

### CODE REVIEW

**Comment by dmsnell** [comment]
thanks @ryanwelcher - I am having a hard time seeing what you want to change because this patch has reformatted all of the code. can you remove all of the formatting/styling changes?

**Comment by ryanwelcher** [comment]
Sorry @dmsnell, i have auto formatting turned on in VSCode and didn't check the diff. Updated.

**Review by dmsnell — APPROVED** [review]
Thanks @ryanwelcher. I checked if this would always be necessary, such as the case with inline images. I realized that they are stored in RichText and not as a block. Perhaps there is a class name Gutenberg adds to make images flow, but for now, this seems like a solid improvement. Thank you.

**Comment by dmsnell** [comment]
Merged in 372b882

**Pull request closed without merging**
